server:
  port: 8081

spring:
  application:
    name: delivery-management-service
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/deliveries
    password: 'root'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: true
